Gift.create(name: "DisneySea", description: "Parque temático da Disney exclusivo do Japão com temática aquática", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/disneysea_fstyit.png", price: 350, remaining_quota: 2)
Gift.create(name: "Passeio de Barco Krabi", description: "Passeio pelas 4 Ilhas de Krabi", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/krabi_wcuq1n.png", price: 240, remaining_quota: 2)
Gift.create(name: "Passeio de Barco Phi Phi", description: "Passeio pelas Ilha de PhiPhi", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588856/phiphi_awz6qx.jpg", price: 170, remaining_quota: 2)
Gift.create(name: "Santuário de Elefantes", description: "Dia com passeio para conhecer, alimentar e dar banho em elefantes", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/elephant_nxk66t.png", price: 200, remaining_quota: 2)
Gift.create(name: "Parque Naruto", description: "Parque temático do universo de Naruto", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/naruto_p3jtc1.jpg", price: 140, remaining_quota: 2)
Gift.create(name: "Universal Studios Japan", description: "Parque temático da Universal incluindo o Super Mario World", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588854/usj_hjwswa.jpg", price: 325, remaining_quota: 2)
Gift.create(name: "Jantar de Sushi especial", description: "Jantar em Restaurante com 1 estrela Michelin", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/kiraku_m86cvp.jpg", price: 200, remaining_quota: 2)
Gift.create(name: "Nagashima Spa Land", description: "Maior parque temático do Japão com a montanha russa mais longa do mundo", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588856/nagashima_xtcgci.png", price: 230, remaining_quota: 2)
Gift.create(name: "Fuji Q", description: "Parque temático aos pés do monte Fuji com 3 montanhas russas do Guinness", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588854/fujiq_lklyze.jpg", price: 220, remaining_quota: 2)
Gift.create(name: "Almoço Pokémon Café", description: "Almoço temático no Pokemon Café", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588856/pokemon_tjdbst.jpg", price: 125, remaining_quota: 2)
Gift.create(name: "Nabana no Sato", description: "Jantar e visita a parque com show de luzes e repleto de flores", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/nabana_qcsul7.jpg", price: 180, remaining_quota: 2)
Gift.create(name: "Diária Hotel na Floresta", description: "2 Diárias em uma casa da árvore na floresta", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/khaosok_h5crno.png", price: 125, remaining_quota: 4)
Gift.create(name: "Passeio Parque Khao Sok", description: "Passeio de 1 dia pelo lago com pernoite nos chalés rústicos", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/lake_zuhiux.jpg", price: 370, remaining_quota: 2)
Gift.create(name: "Massagem Tailandesa", description: "45 minutos de massagem para casal", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588856/massage_djc9e3.png", price: 75, remaining_quota: 2)
Gift.create(name: "2 Diárias em Resort de Luxo", description: "Resort Luxuoso e reservado em Koh Yao", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588856/santhiya_jdhqnh.jpg", price: 97, remaining_quota: 8)
Gift.create(name: "Almoço de Kobe Beef", description: "Almoço especial em restaurante em Kobe", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/kobe_d6zvwy.jpg", price: 145, remaining_quota: 2)
Gift.create(name: "Vilarejo Shirakawa-Go", description: "Passeio de meio dia pelo vilarejo de Shirakawa-Go", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588854/shirakawago_ly8wew.jpg", price: 200, remaining_quota: 2)
Gift.create(name: "Experiência de Kimono", description: "Aluguel de 1 dia de kimonos", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/kimono_a2ltwo.jpg", price: 150, remaining_quota: 2)
Gift.create(name: "Diária em Ryokan", description: "Diária em hotel tradicional japonês com águas termais", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588854/hirayu_s17cus.jpg", price: 185, remaining_quota: 2)
Gift.create(name: "Diária em Templo", description: "Diária em templo budista com café e jantar vegetariano na montanha de Koya", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1624588855/koya_yzn0bb.jpg", price: 204, remaining_quota: 4)
Gift.create(name: "Passagem aérea", description: "Passagens de ida e volta para Japão e Tailândia para 2 pessoas", country: "Japão/Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625440897/Design_sem_nome_pubcas.png", price: 500, remaining_quota: 20)
Gift.create(name: "Dreamworld", description: "Parque de diversões com várias parques temáticas de monumentos e filmes", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/dreamworld_ek7kqu.png", price: 130, remaining_quota: 2)
Gift.create(name: "Siam Niramit", description: "Espetáculo de dança e atuações", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/siam_ivbakb.png", price: 200, remaining_quota: 2)
Gift.create(name: "teamLab Borderless", description: "Exposição interativa com luzes e imagens", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/teamlabs_iqx5pg.png", price: 120, remaining_quota: 2)
Gift.create(name: "Templos de Kyoto", description: "Passeio pelos templos de Ginkakuji, Kinkakuji, Eikando, Tofukuji e Tenryuji", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/templos_h6urw1.png", price: 125, remaining_quota: 2)
Gift.create(name: "Cruzeiro", description: "Cruzeiro com jantar pelo rio de Chao Phraya", country: "Tailândia", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/cruzeiro_vne2ob.png", price: 130, remaining_quota: 2)
Gift.create(name: "Shikansen", description: "Transporte de trem-bala entre Tóquio e Quioto", country: "Japão", picture: "https://res.cloudinary.com/dt7akujlg/image/upload/v1625442300/trem_lvkvzo.png", price: 440, remaining_quota: 2)
Guest.create(name: "Simone Gonçalves e Família", lodging: 2)
Guest.create(name: "Douglas e Familia", lodging: 2)
Guest.create(name: "Felipe", lodging: 2)
Guest.create(name: "Thaís e Familia", lodging: 2)
Guest.create(name: "Stefani e Wendel", lodging: 2)
Guest.create(name: "Leandro Santos", lodging: 2)
Guest.create(name: "Claudia Gonçalves e Família", lodging: 0)
Guest.create(name: "Ryan e Lais", lodging: 2)
Guest.create(name: "Wanderson e Stefani", lodging: 2)
Guest.create(name: "Augusto e Maria", lodging: 2)
Guest.create(name: "Vinicius e Leydjane", lodging: 2)
Guest.create(name: "Thiago e Fabíola ", lodging: 2)
Guest.create(name: "Rafael e Alana", lodging: 2)
Guest.create(name: "Emerson e Andressa", lodging: 2)
Guest.create(name: "Jonas e Luana", lodging: 2)
Guest.create(name: "Felipe e Victoria", lodging: 2)
Guest.create(name: "Caroline", lodging: 2)
Guest.create(name: "Gilberto", lodging: 2)
Guest.create(name: "Paula e Felipe", lodging: 2)
Guest.create(name: "Patrícia", lodging: 2)
Guest.create(name: "Jonathan e Graziele", lodging: 2)
Guest.create(name: "Flavio e Victor", lodging: 2)
Guest.create(name: "Cecilia e Júlio ", lodging: 0)
Guest.create(name: "Leandro Scatamburlo e Familia", lodging: 0)
Guest.create(name: "Rafael e Giselle ", lodging: 0)
Guest.create(name: "Joel e Familia", lodging: 0)
Guest.create(name: "Vinicius", lodging: 2)
Guest.create(name: "Eric e Familia", lodging: 2)
Guest.create(name: "Ana Lídia ", lodging: 2)
Guest.create(name: "Laura e Familia", lodging: 1)
Guest.create(name: "Claudia Moura", lodging: 2)
Guest.create(name: "Fernando", lodging: 2)
Guest.create(name: "Lourdes", lodging: 1)
Guest.create(name: "Marcelo e Família", lodging: 1)
Guest.create(name: "Wanderlei e Família", lodging: 1)
Guest.create(name: "Fernanda", lodging: 2)
Guest.create(name: "Socorro e Família ", lodging: 1)
Guest.create(name: "Tatiana e Renato", lodging: 0)
Guest.create(name: "Edilaneide e Família ", lodging: 1)
Guest.create(name: "Daisy", lodging: 1)
Guest.create(name: "Elivalda", lodging: 1)
Guest.create(name: "Ana Meire e Família", lodging: 1)
Guest.create(name: "Marcos Moura e Família", lodging: 1)
Guest.create(name: "Rosicleide e Roger", lodging: 1)
Guest.create(name: "Rosicler e Odair", lodging: 1)
Guest.create(name: "Thayssa e André", lodging: 1)
Guest.create(name: "Thiago e Família", lodging: 1)
Guest.create(name: "Ivanete e Família", lodging: 2)
Guest.create(name: "Hosana e Família", lodging: 2)
Guest.create(name: "Isabel", lodging: 2)
Guest.create(name: "Adauto e Família", lodging: 2)
Guest.create(name: "Marina e Felipe", lodging: 2)
Guest.create(name: "Natalia e Thiago", lodging: 2)
Guest.create(name: "Raisa e Família", lodging: 2)
Guest.create(name: "Jaqueline e Família", lodging: 2)
Guest.create(name: "Alexandre e Samara", lodging: 2)
Guest.create(name: "Nitay e Ana Paula", lodging: 2)
Guest.create(name: "André", lodging: 2)
Guest.create(name: "Leandro Dorta e Família", lodging: 2)
Guest.create(name: "Ana Cristine e Família", lodging: 0)
Guest.create(name: "Christine e Hélio", lodging: 1)
Guest.create(name: "Simone e Jorge", lodging: 1)
Guest.create(name: "Edenize e Cláudio", lodging: 1)
Guest.create(name: "Cacilda e José Luis", lodging: 1)
Guest.create(name: "Gisele", lodging: 1)
Guest.create(name: "Vânia e Família", lodging: 2)
Guest.create(name: "Renata e Cristiano", lodging: 2)
Guest.create(name: "Caroline e Christian", lodging: 2)
Guest.create(name: "Ana Paula e Família", lodging: 0)
Guest.create(name: "Camila e Família", lodging: 0)
Guest.create(name: "Cristina e Marcel", lodging: 0)
Guest.create(name: "Heloísa e Isadora", lodging: 0)
Guest.create(name: "Raimunda e Miguel", lodging: 0)
Guest.create(name: "Robinson", lodging: 2)
Guest.create(name: "Rogério", lodging: 2)
Guest.create(name: "Débora e Maurício", lodging: 1)
Guest.create(name: "Leonilda e Yuri", lodging: 1)
Guest.create(name: "Valdir e Sandra", lodging: 0)
Guest.create(name: "Miriam", lodging: 1)
Guest.create(name: "Nathalia", lodging: 0)
Guest.create(name: "Geórgia", lodging: 0)
Guest.create(name: "Marcio e Família", lodging: 0)
Guest.create(name: "Thales e Família", lodging: 0)
Guest.create(name: "Camila", lodging: 0)
Guest.create(name: "Fábio e Família  ", lodging: 0)
Guest.create(name: "Guilherme e Fernanda", lodging: 0)
